service: voting-crowdfunding-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    NODE_ENV: local
  memorySize: 512
  timeout: 30

functions:
  createUpdateProposal:
    handler: src/handlers/proposal.createUpdateProposal
    events:
      - http:
          path: proposals
          method: post
          cors: true

  reviewProposal:
    handler: src/handlers/review.reviewProposal
    events:
      - http:
          path: proposals/{proposalID}/review
          method: post
          cors: true
        
  invest:
    handler: src/handlers/investment.invest
    events:
      - http:
          path: investments
          method: post
          cors: true

  vote:
    handler: src/handler.vote
    events:
      - http:
          path: /vote
          method: get
          cors: true

  comment:
    handler: src/handler.comment
    events:
      - http:
          path: /comment
          method: get
          cors: true

  comentar:
    handler: src/handler.comentar
    events:
      - http:
          path: proposals/{id}/comment
          method: post
          cors: true

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3000
    noPrependStageInUrl: true
    noTimeout: true
    allowCache: false
    useChildProcesses: false
